# Generated by Django 4.2.2 on 2023-06-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.BinaryField(null=True)),
                ('player0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fisrt', to='game.player')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Second', to='game.player')),
                ('win', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Win', to='game.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
